version: 2
jobs:
  build:
    docker:
      - image: renovate/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker images
          command: ./build.sh
workflows:
  version: 2
  build:
    jobs:
      - build
